# Generated by Django 2.1.2 on 2018-12-30 15:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publicTime', models.DateTimeField()),
                ('publicContent', models.TextField()),
                ('visitCount', models.IntegerField(default=0)),
            ],
            managers=[
                ('newsManage', django.db.models.manager.Manager()),
            ],
        ),
    ]
