# Generated by Django 2.1.2 on 2018-12-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-publicTime']},
        ),
        migrations.AlterModelTable(
            name='newsitem',
            table='newsItem',
        ),
    ]
